CREATE TABLE IF NOT EXISTS combustivel
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT combustivel_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS posto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    bairro character varying(255),
    cep character varying(255),
    cidade character varying(255),
    endereco character varying(255),
    estado character varying(255),
    latitude character varying(255),
    longitude character varying(255),
    nome character varying(255),
    numero_endereco bigint,
    CONSTRAINT posto_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS preco_combustivel
(
    id_posto bigint NOT NULL,
    id_combustivel integer NOT NULL,
    valor double precision,
    dh_inclusao timestamp without time zone,
    CONSTRAINT preco_combustivel_pkey PRIMARY KEY (id_posto, id_combustivel),
    CONSTRAINT id_combustivel_fk FOREIGN KEY (id_combustivel)
        REFERENCES public.combustivel (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT id_posto_fk FOREIGN KEY (id_posto)
        REFERENCES public.posto (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS avaliacao
(
    id_posto bigint NOT NULL,
    media double precision,
    quantidade_avaliacao integer,
    CONSTRAINT avaliacao_pkey PRIMARY KEY (id_posto),
    CONSTRAINT id_posto_fk FOREIGN KEY (id_posto)
        REFERENCES public.posto (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

CREATE TABLE IF NOT EXISTS avaliacao_historico
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_posto bigint,
    nota integer,
    dh_inclusao timestamp without time zone,
    CONSTRAINT avaliacao_historico_pkey PRIMARY KEY (id),
    CONSTRAINT id_posto_fk FOREIGN KEY (id_posto)
        REFERENCES public.posto (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)